import React, { useState } from "react";

export const ProductContext = React.createContext();

const ContextProvider = ({ children }) => {
  const [cart, setCart] = useState([]);
  const [factor, setFactor] = useState([]);

  // const UID = () => `${new Date().getTime()}${String(Math.random()).slice(3, 9)}`;
  const [userData, setUserData] = useState({
    name: "",
    email: "",
    password: "",
    confirmPassword: "",
    isAccepted: false,
  });
  const [products, setProducts] = useState([
    {
      id: 1,
      name: "galaxy M22",
      price: 4800000,
      company: "Samsung",
      rate: 4.4,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 2,
      name: "galaxy A52",
      price: 5800000,
      company: "Samsung",
      rate: 4.7,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 3,
      name: "galaxy S21",
      price: 23000000,
      company: "Samsung",
      rate: 4.9,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 4,
      name: "galaxy A12",
      price: 5600000,
      company: "Samsung",
      rate: 3.9,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 5,
      name: "poco M3",
      price: 5200000,
      company: "Xiaomi",
      rate: 4.8,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 6,
      name: "poco M4 5G",
      price: 6800000,
      company: "Xiaomi",
      rate: 4.1,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 7,
      name: "redmi 9t",
      price: 5800000,
      company: "Xiaomi",
      rate: 4.5,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 8,
      name: "redmi 8 pro",
      price: 4500000,
      company: "Xiaomi",
      rate: 4.7,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 9,
      name: "redmi 9A",
      price: 3800000,
      company: "Xiaomi",
      rate: 3.5,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 10,
      name: "redmi 9C",
      price: 3500000,
      company: "Xiaomi",
      rate: 3.2,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 11,
      name: "galaxy M12",
      price: 4900000,
      company: "Samsung",
      rate: 2.9,
      color: { blue: false, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 12,
      name: "galaxy A22",
      price: 5800000,
      company: "Samsung",
      rate: 4.2,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 13,
      name: "galaxy M20",
      price: 5400000,
      company: "Samsung",
      rate: 3.8,
      color: { blue: false, black: true, gold: false, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 14,
      name: "galaxy A50",
      price: 5600000,
      company: "Samsung",
      rate: 4.1,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 15,
      name: "poco M3 5G",
      price: 5500000,
      company: "Xiaomi",
      rate: 4.2,
      color: { blue: true, black: true, gold: false, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 16,
      name: "poco M4",
      price: 6100000,
      company: "Xiaomi",
      rate: 3.9,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 17,
      name: "redmi 9",
      price: 5000000,
      company: "Xiaomi",
      rate: 3.8,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 18,
      name: "redmi 8 ",
      price: 4000000,
      company: "Xiaomi",
      rate: 4.4,
      color: { blue: true, black: true, gold: false, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 19,
      name: "redmi 10",
      price: 6800000,
      company: "Xiaomi",
      rate: 4.0,
      color: { blue: true, black: true, gold: true, white: false },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 20,
      name: "Mi 10",
      price: 10000000,
      company: "Xiaomi",
      rate: 4.2,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 21,
      name: "Mi 11",
      price: 12000000,
      company: "Xiaomi",
      rate: 4.4,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
    {
      id: 22,
      name: "Mi 11 Ultra",
      price: 14000000,
      company: "Xiaomi",
      rate: 4.7,
      color: { blue: true, black: true, gold: true, white: true },
      isFavorite: false,
      isInCart: false,
      image: require("../img/Galaxy-A52.jpg"),
      attributes: {
        Dimensions: "155.7×74.5×7.9",
        weight: "186 gramme",
        simNumber: "two",
        memory: "128 GB",
        screenSize: "6.0 inch",
        networks: "2G, 3G, 4G",
        chip: "Exynos 2100 5G Chipset",
        cpu: "1x Cortex-X1 &amp; ۳x Cortex-A78 &amp; 4x Cortex-A55",
        processorType: "64 bits",
        gpu: "Mali-G78 MP14",
        internalMemory: "256 GB",
        ram: "8 GB",
        memoryCardSupport: "No memory card support",
        displayTechnology: "Dynamic AMOLED 2X",
        resolution: "1080×2400",
        photoResolution: "12 megapixels",
        os: "Android",
        osVersion: "Android 12",
        batterySpecifications:
          "Lithium-polymer battery with a capacity of 4500 mAh Supports 25-watt charger with fast charging technology Supports 15-watt wireless charger Supports reverse charging technology",
      },
      about:
        "The FE series of Samsung smartphones have gained a lot of fans due to their convenient and powerful technical specifications and, of course, at a more affordable price than the company's flagships, and they have been able to show very good and acceptable performance. Samsung Galaxy S21 FE 5G, as the newest smartphone in this series, is also equipped with powerful and very good technical specifications. In front view, this phone has a 6.4-inch display with a resolution of 1080 x 2400 pixels of Dynamic AMOLED 2X type. So far, it's clear that this phone is equipped with one of the most powerful screens, but when you realize the true power of this screen, you know that it has the ability to display 411 pixels per inch and a maximum refresh rate of 120 Hz. On the back, there is a main camera sensor with a resolution of 12 megapixels and an aperture of f / 1.8, along with an 8-megapixel telephoto sensor with optical triple zoom (zoom without loss of quality) and a 12-megapixel ultra-wide sensor (ultraw). With a viewing angle of 123 degrees, the sensors form the Samsung Galaxy S21 FE 5G triple camera. For the selfie camera, a sensor with a resolution of 32 megapixels is considered wide. In terms of hardware specifications, this phone has also entered the competition with a full hand. The presence of the Exynos 2100 5G processor has enabled the Samsung Galaxy S21 FE 5G to run heavy games such as mobile add-ons and asphalt 9 easily and perform very well. On the other hand, this processor has the ability to support the fifth generation or 5G Internet networks. A battery with a capacity of 4500 mAh and a 25 watt charger equipped with fast charging technology are other specifications for this smartphone.",
    },
  ]);

  return (
    <ProductContext.Provider
      value={{
        products,
        setProducts,
        cart,
        setCart,
        userData,
        setUserData,
        factor,
        setFactor,
      }}
    >
      {children}
    </ProductContext.Provider>
  );
};

export default ContextProvider;
